{
 "title": "Булочная",
 "time": { "from": "2025-10-22T12:00:00.000Z", "to": "2025-10-24T12:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "filial",
    "label": "Филиал",
    "query": "SELECT DISTINCT filial \nFROM reviewt_db \nORDER BY filial;"
   }
  ]
 },
 "panels": [
  {
   "title": "Динамика оценки ${filial}",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT\r\n  AVG(mark) AS \"value\",\r\n  DATE_TRUNC('day', created_at) AS \"time\"\r\nFROM\r\n  reviewt_db\r\nWHERE\r\n  filial = '${filial}'\r\nGROUP BY DATE_TRUNC('day', created_at)\r\nORDER BY time\r\nLIMIT\r\n  50"
    }
   ]
  },
  {
   "title": "Общая статистика",
   "type": "table",
   "gridPos": { "h": 13, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT filial, AVG(mark), COUNT(filial) FROM reviewt_db GROUP BY filial LIMIT 50 "
    }
   ]
  },
  {
   "title": "Отзывы",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT\r\n  id,\r\n  filial,\r\n  mark,\r\n  content,\r\n  \"publickName\",\r\n  \"userName\",\r\n  created_at,\r\n  'Подробнее' AS test_with_id,\r\n  media\r\nFROM\r\n  reviewt_db\r\nWHERE filial = '${filial}'\r\nLIMIT\r\n  50"
    }
   ]
  }
 ]
}